#define WIFI_SSID     "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define DEVICE_ID     "iris_01"

#define MQTT_HOST     "YOUR_HIVEMQ_CLUSTER.hivemq.cloud"
#define MQTT_PORT     8883
#define MQTT_USERNAME "YOUR_MQTT_USERNAME"
#define MQTT_PASSWORD "YOUR_MQTT_PASSWORD"
